### $Id: Makefile,v 1.1.1.1 2000/06/08 00:10:03 afikes Exp $

OBJ_FILES = create_osuif_hello_world.o

SRCS = create_osuif_hello_world.cpp

PROGRAM = create_osuif_hello_world

LIBS += -liokernel -lsuifkernel -lsuifnodes -lbasicnodes -lcommon -losuifnodes \
	-ltypebuilder

include ../Makefile.osuif
