TARGET =	visual_tcl_lib
SUPER_PACKAGES_PATH = suifbrowser
TCLSRCS =	vpopup.tcl vselectfile.tcl vdefaults.tcl \
		vdialog.tcl vform.tcl vframe.tcl vgraph.tcl visual.tcl \
		vlistbox.tcl vmenu.tcl vmessage.tcl vmisc.tcl vtext.tcl \
		vtoplevel.tcl vhtml.tcl vbuttonbar.tcl
OTHERSRCS =	visual.rc

all:		source
install-bin:	install-bin-base

include $(NCIHOME)/Makefile.std
