/*--------------------------------------------------------------------
 * output_viewer.h
 *
 * The output_viewer displays C output generated by s2c.
 * There should be `line' annotations embedded as comments in the C
 * file, so that the viewer can map the output lines back to Suif.
 *
 */

#ifndef OUTPUT_VIEWER_H
#define OUTPUT_VIEWER_H

#include "code_tree.h"
#include "base_viewer.h"

class scope_node;
typedef list<scope_node*> scope_node_list;

/*
 * output viewer
 */
class output_viewer : public text_base_viewer {
  typedef text_base_viewer inherited;

  static const String empty_file;

  String current_file;

  vmessage*        infobar;  
  code_tree*       outtree;
  FileBlock*      current_fse;
  scope_node_list* proc_scopes;

  static void do_open_cmd( event& e, output_viewer* viewer );
  static code_range map_tree_node( SuifObject* tn, output_viewer* viewer );

  virtual void erase_mappings();
  virtual bool print_output( String filename );
  virtual void update_infobar();
  virtual void show( vnode* vn );

public:
  output_viewer();
  virtual ~output_viewer();

  virtual void create_window();

  virtual char* class_name() { return "Output Viewer"; }
  virtual void handle_event( event& e );

  virtual void clear();
  virtual void view( FileBlock* fb, String out_file = String() );
  virtual void view( SuifObject* node, bool select = true );

//@@@  /* state of viewer */
//@@@  code_tree* output_tree() { return outtree; }

  static window* constructor() {
    return new output_viewer;
  }
};

#endif
