### $Id: Makefile,v 1.1.1.1 2000/06/08 00:10:02 afikes Exp $

PACKAGES =	vtblnodes \
		vtblpass \
		instancefieldslayoutnodes \
		instancefieldslayoutpass \
		lowering \
		print 
# lowering-passes


include ../Makefile.osuif
