### $Id: Makefile,v 1.1.1.1 2000/06/08 00:10:03 afikes Exp $

SRCS =		type_builder.cpp
HEADERS =	type_builder.h
OBJ_FILES =	type_builder.o

TARGET_LIB = osuiftypebuilder

LIBS += -losuifnodes -losuifextensionnodes \
	-lutils \
	-lsuifnodes -lsuifkernel -liokernel -lbasicnodes -lcommon


include ../Makefile.osuif
