### $Id: Makefile,v 1.3 2000/06/11 03:03:13 lam Exp $

PACKAGES =	osuifnodes \
		osuifextensionnodes \
		typebuilder \
		utilities \
		passes \
		samples \
		cpp_osuif 

include $(OSUIFHOME)/Makefile.osuif
