PACKAGES =  common  tools  basesuif  utils  cfeutils basepasses extratypes

PACKAGES += `grep -v '^\#' extra_suif_packages`

ifneq (,$(BUILDDOCS))
PACKAGES += doc
endif

include $(NCIHOME)/Makefile.std






